name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build deps
      run: sudo apt-get install premake4 libglfw3-dev libglu1-mesa-dev
    - name: premake
      run: premake4 gmake
    - name: make
      run: |
        cd build
        make
    - name: run example2
      run: |
        cd build
        ./example2
